---
title: "Data Tidying"
author: "Shun Xie"
date: "2022-09-27"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Load packages
```{r}
library(tidyverse)

options(tibble.print_min = 5)
```


```{r}
pulse_df = 
  haven::read_sas("./data/public_pulse_data.sas7bdat") %>%
  janitor::clean_names()
pulse_df
```


```{r}
#the column you want to combined into one column
pulse_tidy_data = 
  pivot_longer(
    pulse_df, 
    bdi_score_bl:bdi_score_12m,
    names_to = "visit", 
    values_to = "bdi")
pulse_tidy_data
```

```{r}
pulse_tidy_data = 
  pivot_longer(
    pulse_df, 
    bdi_score_bl:bdi_score_12m,
    names_to = "visit", 
    names_prefix = "bdi_score_",
    values_to = "bdi")

pulse_tidy_data

```



```{r}

```





```{r}
pulse_tidy_data = 
  pivot_longer(
    pulse_df, 
    bdi_score_bl:bdi_score_12m,
    names_to = "visit", 
    names_prefix = "bdi_score_",
    values_to = "bdi") %>%
  mutate(visit = replace(visit,visit=='bl','00m'),
         visit = factor(visit)) %>%
  arrange(id, visit)

pulse_tidy_data
```

```{r}
litters_wide = 
  read_csv("./data/FAS_litters.csv") %>%
  janitor::clean_names() %>%
  select(litter_number, ends_with("weight")) %>%
  #the two column merge to one column
  pivot_longer(
    gd0_weight:gd18_weight,
    names_to = "gd", 
    values_to = "weight") %>% 
  #rename gd0 as numerical value 0 and gd18 as numerical value 18
  mutate(gd = recode(gd, "gd0_weight" = 0, "gd18_weight" = 18))
```

```{r}
litters_wide
```


```{r}
analysis_result = tibble(
  group = c("treatment", "treatment", "placebo", "placebo"),
  time = c("pre", "post", "pre", "post"),
  mean = c(4, 8, 3.5, 4)
)
view(analysis_result)
```

change into wide format. split a column into columns with respect to names in the column. 

```{r}

analysis_result_wide = pivot_wider(
  analysis_result, 
  names_from = "time", 
  values_from = "mean")
```



```{r}
fellowship_ring = 
  readxl::read_excel("./data/LotR_Words.xlsx", range = "B3:D6") %>%
  mutate(movie = "fellowship_ring")

two_towers = 
  readxl::read_excel("./data/LotR_Words.xlsx", range = "F3:H6") %>%
  mutate(movie = "two_towers")

return_king = 
  readxl::read_excel("./data/LotR_Words.xlsx", range = "J3:L6") %>%
  mutate(movie = "return_king")
```

```{r}
# all the columns in three dataframe have the same name, so can bind rows. 
lotr_tidy = 
  bind_rows(fellowship_ring, two_towers, return_king) %>%
  janitor::clean_names() %>%
  # bind to the column
  pivot_longer(
    female:male,
    names_to = "gender", 
    values_to = "words") %>%
  mutate(race = str_to_lower(race)) %>%  
  select(movie, everything()) 
```


# Joining Dataframe
```{r}
pups = read_csv('./data/FAS_pups.csv')  %>%
  janitor::clean_names() %>%
  mutate(sex=recode(sex, '1'='male', '2'='female'),
  sex = factor(sex))
  
```


```{r}
pup_data = 
  read_csv("./data/FAS_pups.csv") %>%
  janitor::clean_names() %>%
  mutate(
    sex = recode(sex, `1` = "male", `2` = "female"),
    sex = factor(sex)) 

litter_data = 
  read_csv("./data/FAS_litters.csv") %>%
  janitor::clean_names() %>%
  separate(group, into = c('dose',"day_of_tx"), sep = 3) %>%
  relocate(litter_number) %>%
  mutate(
    wt_gain = gd18_weight - gd0_weight,
    dose = str_to_lower(dose))
view(litter_data)
```



```{r}
fas_data = left_join(pup_data, litter_data,by='litter_number')
```





