---
title: "Data Import"
output: html_document
---

```{r}
library('tidyverse')
library('readxl')
library('haven')
```



## Data Import: CSVs

Let's import data using the 'readr' package.
```{r}
litter_df <- read_csv('data/FAS_litters.csv')
litter_df <- janitor::clean_names(litter_df) #use clean_names from specifically janitor packages


```

```{r}
litter_df

head(litter_df)
tail(litter_df)

```

```{r,eval=FALSE}
view(litter_df)

```


```{r}
skimr::skim(litter_df)
```


"read_csv" options:

```{r}
litter_NA_df <- read_csv('data/FAS_litters.csv', na = c("","NA",999,88),skip = 2)

```



## Other file format

We need to read in an excel document

```{r}
mlb.df <- read_excel('data/mlb11.xlsx')
```

```{r,eval = FALSE}
view(mlb.df)
```

```{r}
intr_words_df=read_excel("data/mlb11.xlsx",range="B3:D6")
```


## Still More formats...
Read in a SAS format:

```{r}
pulse_df <- read_sas("data/public_pulse_data.sas7bdat")
```

## Data export

```{r}
write_csv(intr_words_df,file = "results/intr_words_df.csv")
```



## why not base r???

```{r}
#dont use read.csv, instead use read_csv
dont_do_this_df = read.csv("data/FAS_litters.csv")
```

















